### ISSUE TITLE
Promotion policy functional tests sometimes fail on AWS-EC2

### ISSUE THREAD

**Issue by KamilLepek** [Open-CAS/ocf#271]
https://d1rxsi9lvcwnz5.cloudfront.net/index.html?project=ocf&pr=264&category=functional-tests&run=567

This seems to occur in random configurations once a while. Couldn't get a local reproduction.

**Comment by robertbaldyga** [comment]
This seems to be really rare. It happened again after more that one year:
https://d1rxsi9lvcwnz5.cloudfront.net/index.html?project=ocf&pr=434&category=functional-tests&run=976
