### ISSUE TITLE
Please help describe the IO procedures of CAS

### ISSUE THREAD

**Issue by beef9999** [Open-CAS/ocf#374]
```
ocf_core_submit_io
    ocf_volume_submit_io
        volume->type->properties->ops.submit_io
            ocf_core_volume_submit_io
                ocf_engine_hndl_req
                    ocf_queue_run
                        ocf_io_handle
                            ocf_write_wt  // req->io_if->write
                                _ocf_write_wt_do
                                    _ocf_write_wt_submit    
                                        ocf_submit_cache_reqs
                                            ocf_volume_submit_io    
```
Looks like the final `ocf_volume_submit_io` traverses back to the beginning.
So I guess the CAS IO is a run-to-completion design? And where should it block if there is no incoming IO?

**Comment by robertbaldyga** [comment]
That's because both core and backend device are represented by `ocf_volume_t`. So the first call to `ocf_volume_submit_io()` passes io to the caching engine, while second one submits io to the actual backend device.

**Comment by beef9999** [comment]
As far as I can see now, the IO procedures are as below (for instance,  a write-back write):
kernel blk-mq -> fast path engine
(hit) go to the write-back engine, then invoke `ocf_submit_cache_reqs`
(miss) fall back to kernel IO scheduler, call `submit_io` registered by `cas_object_blk_properties`, then finally invoke `kernel submit_bio`

My question is, there is only one `kernel submit_bio` which is used by the core device, so who is responsible for writing the SSD cache device? I looked through all the engine and metadata code and didn't find any potential functions that could perform a write.

**Comment by beef9999** [comment]
Which engine is for backend device? d2c?

**Comment by beef9999** [comment]
Which engine is for backend HDD device? d2c?

The logic that decides whether to use d2c is really strange.
