### ISSUE TITLE
Metadata invalid checksum error after power failure during cache stop sequence

### ISSUE THREAD

**Issue by michalwy** [Open-CAS/ocf#391]
When power failure occurs during cache stopping, it's possible that there would be invalid metadata checksum on next cache load.

If in cache shutdown sequence power failure occurs after sb_runtime and/or part_runtime segments are flushed, but before final sb_config flush, there might be metadata checksum error for those segments on next cache load. 
Checksums for those segments are verified in load sequence regardless of shutdown status - dirty or clean. They should be checked only after clean shutdown. For dirty shutdown there is no guarantee that checksums for those segments are up to date.

**Comment by gwnet** [comment]
@michalwy PRC JD customer mentioned that 20.03 has the same issue. we are waiting the patch for issue 390 and 391. may I who can arrange the patch release process, how long it will take?
JD is PRC 2nd large etrade company, there is O chance for us. :)

**Comment by beef9999** [comment]
@michalwy I have met this kind of errors as well. But my program was gracefully shutdown.

https://github.com/Open-CAS/ocf/issues/565
