### ISSUE TITLE
Need some clarification for promotion feature

### ISSUE THREAD

**Issue by hertz1987** [Open-CAS/ocf#415]
In Open CAS there is a feature called "promotion" which didn't existed in Intel CAS, I've went through the documentation and it said "This parameter specifies the desired promotion policy of core lines", but still I don't know what it is and how this parameter would affect core line. Maybe Adding some little extra description of such concept to the "Basic concepts"  section of this page : [https://open-cas.github.io/ocf_intro.html](OpenCAS Introduction) would be very helpful?

**Comment by Deixx** [comment]
Hi @hertz1987, 

Just to give you the answer quickly - promotion policy determines how core lines are inserted into cache. There are 2 options, which can be set with 'casadm --set-param --name promotion ...' command:
1. 'always' - default behavior, works exactly the same as before - each access to a core line promotes it to cache (if cache mode allows for it)
2. 'nhit' - promotes core lines after accessing them n times. Also allows for setting a cache occupancy level at which nhit policy will start working. Both the number of accesses (the threshold) and the occupancy level (the trigger) can be set with 'casadm --set-param --name promotion-nhit ...' command.
Command structure is described in casadm man page.

**Comment by hertz1987** [comment]
@Deixx That explained everything for me，thank you!
