### ISSUE TITLE
Question about alru cleaning

### ISSUE THREAD

**Issue by mq0427** [Open-CAS/ocf#416]
I have one question about alru cleaning while reading codes about alru cleaning recently. strcut alru_cleaning_policy_meta could be accessed concurrently when doing alru cleaning and when also a write request hits cache and ocf_cleaning_set_hot_cache_line is called to update alru list. So it seems possible that when cleaning thread traverse alru list, the lru_prev or lru_next could be changed in case of cache line hit. I think there should be a lock or something to handle this race condition. But I could not find it in ofc codes. Am I missing anything?  Could you please help to explain that?

**Comment by imjfckm** [comment]
Hi @mq0427.

`struct alru_cleaning_policy_meta` is guarded by per-partition(ioclass) spinlock (`cache->cleaner.cleaning_policy_context.list_lock`) and it is used both in `cleaning_policy_alru_set_hot_cache_line` and in `get_data_to_flush`, which is called by `alru_clean`. I think it should prevent any collisiton between cleaner iterating the lru list and other write request moving given cache line to head of it. Do you see any chance of that happening regardless of this locks being taken?

**Comment by mq0427** [comment]
Thanks for your reply @imjfckm. That answers my question. I think the spinlock could prevent collisiton.
Another following question from me is what the major difference of ALRU with the standard LRU algorithim? It seems ALRU also maintain lru list and always clean the cache lines starting from least-recently-used ones.

**Comment by arutk** [comment]
Hi @mq0427 
You are right, in our case ALRU is indeed equivalent to LRU. The A in ALRU stands for approximate, meaning that only dirty cachelines are kept on the list, not all of them (which seems obvious for cleaner structure).
