### ISSUE TITLE
How can I disable currently used io class file without having to restart the cache?

### ISSUE THREAD

**Issue by hertz1987** [Open-CAS/ocf#419]
I specified a io class file for a cache but when I decided to disable it there was not option that would allow me to do so, and I had to stop/start the cache to achieve it, so how can I disable currently used io class file, without having to restart the cache?

> root@node195:/etc/opencas# casadm -C -H
> Usage: casadm --io-class {--load-config|--list}
> 
>    Manage IO classes
> 
> 
> Loads configuration for IO classes:
> Usage: casadm --io-class --load-config --cache-id <ID> --file <FILE>
> Options that are valid with --load-config (-C) are:
>    -i  --cache-id <ID>                 Identifier of cache instance <1-16384>
>    -f  --file <FILE>                   Configuration file containing IO class definition
> 
> 
> Lists currently configured IO classes:
> Usage: casadm --io-class --list --cache-id <ID> [option...]
> Options that are valid with --list (-L) are:
>    -i  --cache-id <ID>                 Identifier of cache instance <1-16384>
>    -o  --output-format <FORMAT>        Output format: {table|csv}

**Comment by Deixx** [comment]
Hi @hertz1987,

The only way to change IO class behavior (without restarting cache), is to load modified IO class config file. Resetting to default cache behavior can be achieved by loading below config:
IO class id,IO class name,Eviction priority,Allocation
0,unclassified,255,1
And actually it is what 'casadm -C -L -i <cache id> -o csv' outputs after starting cache without configuring IO classes.

**Comment by hertz1987** [comment]
Personally I think this method is not very much user-friendly, but it helps with the problem, thank you for your answer!
