### ISSUE TITLE
[example bug] v21.3.3 example code is not working at all

### ISSUE THREAD

**Issue by beef9999** [Open-CAS/ocf#564]
1. The example code in v21.3.3 is not working at all. A floating point exception will occur, because the `ocf_mngt_cache_device_config_set_default` has set a zero cache-line size by default. 

2. Even after setting `device_cfg.cache_line_size = ocf_cache_line_size_default` correctly, the example code will still hang in the final stopping cache step.

3. v20.3.4 is OK

**Comment by gaowayne** [comment]
@robertbaldyga looks like our example code is broken. can we fix it?

**Comment by arutk** [comment]
there remains the problem of deadlock during cache stop in the example. this is due to lack of proper queue (threads) implementation in the example. OCF requires actual asynchronous execution of the pipeline steps and the sample fails to provide that.

**Comment by beef9999** [comment]
@arutk 
> OCF requires actual asynchronous execution

But why v20.3.4 was OK?

And if it's true, anyway, could it also be the root cause of https://github.com/Open-CAS/ocf/issues/565 ? In that issue I was testing non-volatile metadata based on the example code as well.
