### ISSUE TITLE
how to configure or run fio with ocf in v20.01.x

### ISSUE THREAD

**Issue by CryusYoung** [Open-CAS/ocf#571]
## Question
setup spdk with ocf and fio( just do as https://open-cas.github.io/getting_started_spdk.html), after setup, environment is ok, but fio can't work, the error is can't find the bdev

my fio script is:
[global]
#ioengine=spdk
ioengine=./examples/bdev/fio_plugin/fio_plugin
#spdk_conf=./examples/bdev/fio_plugin/bdev.conf.in
spdk_conf=xxx.conf.in
thread=1
group_reporting=1
direct=1
verify=0
time_based=1
ramp_time=0
runtime=300
iodepth=1
rw=randwrite
bs=4k

[ocf]
#filename=cache0

#[test]
numjobs=1
#filename=trtype=PCIe traddr=03.00.0 ns=1
#filename=nvme0n1

xxx.conf.in is:
[Split]
 Split Nvme0n1 2 10240
[ocf]
 filename=cache0

i've tried all method i could thought of. i'm here to ask for help.
                                                                                              thx~

**Comment by CryusYoung** [comment]
spdk_fio_setup: *ERROR*: Unable to find bdev with name cache0
that‘s  the errlog

**Comment by rafalste** [comment]
Hi @CryusYoung,
the first thing to consider in your setup is upgrading SPDK to the newer version (ideally the latest one) as we wouldn't support any issues related to OCF older than 20.12 as it is the current version of OCF in SPDK.

The next thing is your SPDK config _xxx.conf.in_ - it is not constructing OCF bdev (_cache0_) as it should, before running fio. It is a good practice to first check if devices are created successfully just by starting SPDK app with a config file.
> Assuming you are determined to use the old SPDK version 20.01, you can do this by issuing:
> `./spdk/app/spdk_tgt/spdk_tgt -c xxx.conf.in`

Then you can check if your devices were created with:
`./spdk/scripts/rpc.py bdev_get_bdevs`

I can't help you with setting up this config file properly, as it is an old (and deprecated probably) config file format. You can reach SPDK team for help on this matter, but I strongly advise you to upgrade SPDK and use the JSON config file format (fio_plugin don't support it in SPDK 20.01). Then your SPDK config file should look like this:
```
{                                                                                                   
  "subsystems": [                                                                                   
    {                                                                                               
      "subsystem": "bdev",                                                                          
      "config": [                                                                                   
        {                                                                                           
          "method": "bdev_nvme_attach_controller",                                                     
          "params": {                                                                               
            "name": "Nvme0",                                                                        
            "trtype": "PCIe",                                                                       
            "traddr": "0000:06:00.0"                                                                
          }                                                                                         
        },                                                                                          
        {                                                                                           
          "method": "bdev_split_create",                                                            
          "params": {                                                                               
            "base_bdev": "Nvme0n1",                                                                 
            "split_count": 2,                                                                       
            "split_size_mb": 10240                                                                  
          }                                                                                         
        },                                                                                          
        {                                                                                           
          "method": "bdev_ocf_create",                                                              
          "params": {                                                                               
            "name": "cache0",                                                                       
            "mode": "wb",                                                                           
            "cache_line_size": 4,                                                                   
            "cache_bdev_name": "Nvme0n1p0",                                                         
            "core_bdev_name": "Nvme0n1p1"                                                           
          }                                                                                         
        }                                                                                           
      ]                                                                                             
    }                                                                                               
  ]                                                                                                 
}
```

**Comment by CryusYoung** [comment]
Hi,@rafalste, thx for your suggestion，I'll upgrade it to newer version in the future.
i still wanna know how the fio work in this version v20.01 because of some reasons.
i'm sure that the envirnment is ok, and devices created correctly,  the command ./spdk/scripts/rpc.py bdev_ocf_get_bdevs shows that my ocf‘s state is correct.  and fio can work with using bdev.conf.in with creating malloc, nvme and ocf in the bdev.conf.in.
the problem is when change the ocf create method to  https://open-cas.github.io/getting_started_spdk.html, fio can't work, i'm just wondering which configuration is wrong

**Comment by rafalste** [comment]
@CryusYoung those instructions in the Open CAS documentation are for creating OCF bdev in SPDK and they should work on recent SPDK versions (they will work with SPDK 20.01 with slight modifications e.g. the path to _spdk_tgt_ binary), but... if you want to run _fio_plugin_ on OCF bdev you need to pass the configuration for it in a config file supplied to fio and not creating those bdevs manually. This is bacause _fio_plugin_ (and even SPDK's native _bdevperf_) is setting up all devices prior running any tests. So, if you create those devices beforehand, there is an attempt to create them once again before running fio, which obviously fails (as devices are in use already) and as a result an error message is printed that _"Unable to find bdev with name cache0"_.
Is that what you were asking?

**Comment by CryusYoung** [comment]
Yes，that's what i wanna to kown. thanks very very much. 发自我的华为手机-------- 原始邮件 --------发件人： rafalste ***@***.***>日期： 2021年9月17日周五 傍晚6:53收件人： Open-CAS/ocf ***@***.***>抄送： CryusYoung ***@***.***>, Mention ***@***.***>主    题： Re: [Open-CAS/ocf] how to configure or run fio with ocf in v20.01.x (#571)
@CryusYoung those instructions in the Open CAS documentation are for creating OCF bdev in SPDK and they should work on recent SPDK versions (they will work with SPDK 20.01 with slight modifications e.g. the path to spdk_tgt binary), but... if you want to run fio_plugin on OCF bdev you need to pass the configuration for it in a config file supplied to fio and not creating those bdevs manually. This is bacause fio_plugin (and even SPDK's native bdevperf) is setting up all devices prior running any tests. So, if you create those devices beforehand, there is an attempt to create them once again before running fio, which obviously fails (as devices are in use already) and as a result an error message is printed that "Unable to find bdev with name cache0".
Is that what you were asking?
