### ISSUE TITLE
Cache performance drop after dirty shutdown

### ISSUE THREAD

**Issue by beef9999** [Open-CAS/ocf#578]
## Question
In the test environment, I found that if the cache was dirty shutdown, the performance would dramatically drop to 15%, compared to a gracefully shutdown.

```
Ease Cache: ERROR: Cache device did not shut down properly!
Ease Cache: Initiating recovery sequence...
Ease Cache: Done loading cache state
```

Then a lot of writes were observed in cache device, seemed the whole cache had become invalid just now, and it took a long time before the performance went to normal.

The API I was calling is merely `ocf_mngt_cache_load`. Did I miss any steps?

**Comment by beef9999** [comment]
@arutk Will it be resolved after introducing metadata journaling?

**Comment by arutk** [comment]
@beef9999 unfortunately no. 

This approach (invalidating clean cachelines after dirty shutdown) is a consequence of how we manage data and metadata updates in OCF. This includes :
  - ordering of in-memory metadata updates relative to data writes to the disk - this is not adressed by journalling, at least not in the approach we were considering
  - flushing metadata from memory to cache drive as part of I/O - currently this is performed only when cacheline clean status changes - this aspect would be adressed by journalling as we will always have the most up-to-date version of metadata in memory after recovery from journal. 

So changing OCF to not require clean cachelines invalidation in recovery would require careful reordering of metadata updates combined with metadata journaling *or* more extensive flushing of metadata from memory to the drive.
