### ISSUE TITLE
IO Class Configuration - Allocation

### ISSUE THREAD

**Issue by wuyan6293** [Open-CAS/ocf#74]
Allocation is an option about the IO Class Configuration in the enterprise edition Intel CAS.
![image](https://user-images.githubusercontent.com/5463273/54367417-499fb280-46ad-11e9-95e7-a083567c1361.png)
But I can't find the same configure option in the open-cas.
```
/**
 * @brief IO class configuration
 */
struct ocf_mngt_io_class_config {
	/**
	 * @brief IO class ID
	 */
	uint32_t class_id;

	/**
	 * @brief IO class name
	 */
	const char *name;

	/**
	 * @brief IO class eviction priority
	 */
	int16_t prio;

	/**
	 * @brief IO class cache mode
	 */
	ocf_cache_mode_t cache_mode;

	/**
	 * @brief IO class minimum size
	 */
	uint32_t min_size;

	/**
	 * @brief IO class maximum size
	 */
	uint32_t max_size;
};
```

1. Does open-cas support the allocation option?
2. What means about the allocation options of the IO class ?

**Comment by michalwy** [comment]
Hi,

At OCF level allocation is controlled through cache_mode field in ocf_mngt_io_class_config struct. You should set cache_mode to pass-through for I/O class for which you don't want to have allocation set to "YES".
Summarizing:

- If you want allocation to be set to "NO" - set cache_mode to ocf_cache_mode_pt
- If you want allocation to be set to "YES" - set cache_mode to any other cache mode or ocf_cache_mode_max (in this case cache mode configured on cache instance would be used).

**Comment by wuyan6293** [comment]
Get it, thank you very much.
