### ISSUE TITLE
Is open cas ocf continuously maintained and updated? Or has open cas ocf become an abandoned project?

### ISSUE THREAD

**Issue by fantastic2085** [Open-CAS/ocf#782]
## Question

Is open cas ocf continuously maintained and updated? Or has open cas ocf become an abandoned project?
## Motivation

The reason why I ask this question is that I want to use opencas to speed up ceph. If opencas is not maintained, it is not considered
## Your Environment

* OCF version (commit hash or tag):
* Operating System:
* Kernel version:
* Cache device type (NAND/Optane/other):
* Core device type (HDD/SSD/other):
* Configuration:
* * Cache mode: (default: wt)
* * Cache line size: (default: 4)
* Other (e.g. _lsblk_, _lsscsi_)

**Comment by robertbaldyga** [comment]
It is currently maintained less intensively than before, but we work on keeping it stable and fix bugs when reported.
